// Generated by React Router v7 - AWS SBG Event Portal Edition
import { useEffect, useRef } from "react";
import type { Route } from "./+types/_index";
import { Hero } from "@/components/landing-page/hero";
import { Divisions } from "@/components/landing-page/divisions";
import { Events } from "@/components/landing-page/events";
import { Team } from "@/components/landing-page/team";
import { Footer } from "@/components/landing-page/footer";

export function meta({}: Route.MetaArgs) {
  return [
    { title: "AWS Student Builder Group | Bahria University Karachi" },
    { name: "description", content: "From Students to Builders. Cloud, AI, and modern software through hands-on building." },
  ];
}

export default function Index() {
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const link = document.createElement("link");
    link.href = "https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@300;400;500;600;700&family=Syne:wght@700;800&display=swap";
    link.rel = "stylesheet";
    document.head.appendChild(link);
  }, []);

  return (
    <div 
      ref={containerRef}
      className="bg-[#030303] text-[#ededed] font-['Plus_Jakarta_Sans',sans-serif] selection:bg-[#FF9900] selection:text-black overflow-x-hidden antialiased"
    >
      {/* GLOBAL HEADER / NAV */}
      <header className="fixed top-0 left-0 w-full z-50 flex justify-between items-center px-6 lg:px-12 py-5 backdrop-blur-xl bg-[#030303]/70 border-b border-white/[0.06]">
        <div className="flex items-center gap-3">
          <div className="w-3 h-3 rounded-full bg-[#FF9900] animate-pulse shadow-[0_0_12px_#FF9900]" />
          <span className="font-['Syne'] font-extrabold text-lg tracking-wider text-white">AWS SBG <span className="text-[#FF9900]">BUK</span></span>
        </div>
        <div className="hidden md:flex items-center gap-8 text-xs tracking-widest uppercase font-semibold text-white/60">
          <a href="#divisions" className="hover:text-white transition-colors cursor-pointer">Divisions</a>
          <a href="#events" className="hover:text-white transition-colors cursor-pointer">Hackathons</a>
          <a href="#divisions" className="hover:text-white transition-colors cursor-pointer">Projects</a>
          <a href="#contact" className="hover:text-white transition-colors cursor-pointer">Team</a>
        </div>
        <a 
          href="#contact" 
          className="px-5 py-2.5 rounded-full text-xs font-bold uppercase tracking-widest bg-white text-black hover:bg-[#FF9900] transition-all duration-300 shadow-[0_0_20px_rgba(255,255,255,0.1)]"
        >
          Join Portal
        </a>
      </header>

      {/* SECTIONS */}
      <Hero />

      {/* INFINITE GREETING MARQUEE STRIP */}
      <div className="py-8 border-y border-white/10 bg-[#050505] overflow-hidden whitespace-nowrap">
        <div className="inline-flex gap-12 animate-[marquee_25s_linear_infinite] text-white/30 font-['Syne'] font-bold text-xl uppercase tracking-widest">
          <span>Hello</span> • <span>Namaste</span> • <span>Hola</span> • <span>Bonjour</span> • <span>Nǐn hǎo</span> • <span>Olá</span> • <span>Shalom</span> • <span>Ciao</span> • <span>Aloha</span> • <span>Xin Chào</span> • <span>Salaam</span> • <span>Zdraveĭte</span>
        </div>
      </div>

      <Divisions />
      <Events />
      <Team />
      <Footer />

      <style>{`
        @keyframes marquee {
          0% { transform: translateX(0%); }
          100% { transform: translateX(-50%); }
        }
      `}</style>
    </div>
  );
}