// Generated by React Router v7 - AWS SBG Event Portal Edition
import { useEffect, useRef } from "react";
import type { Route } from "./+types/_index";

export function meta({}: Route.MetaArgs) {
  return [
    { title: "AWS Student Builder Group | Bahria University Karachi" },
    { name: "description", content: "From Students to Builders. Cloud, AI, and modern software through hands-on building." },
  ];
}

export default function Index() {
  const containerRef = useRef<HTMLDivElement>(null);

  // Injecting high-end typography sheets dynamically
  useEffect(() => {
    const link = document.createElement("link");
    link.href = "https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@300;400;500;600;700&family=Syne:wght@700;800&display=swap";
    link.rel = "stylesheet";
    document.head.appendChild(link);
  }, []);

  return (
    <div 
      ref={containerRef}
      className="bg-[#030303] text-[#ededed] font-['Plus_Jakarta_Sans',sans-serif] selection:bg-[#FF9900] selection:text-black overflow-x-hidden antialiased"
    >
      {/* GLOBAL HEADER / NAV */}
      <header className="fixed top-0 left-0 w-full z-50 flex justify-between items-center px-6 lg:px-12 py-5 backdrop-blur-xl bg-[#030303]/70 border-b border-white/[0.06]">
        <div className="flex items-center gap-3">
          <div className="w-3 h-3 rounded-full bg-[#FF9900] animate-pulse shadow-[0_0_12px_#FF9900]" />
          <span className="font-['Syne'] font-extrabold text-lg tracking-wider text-white">AWS SBG <span className="text-[#FF9900]">BUK</span></span>
        </div>
        <div className="hidden md:flex items-center gap-8 text-xs tracking-widest uppercase font-semibold text-white/60">
          <span className="hover:text-white transition-colors cursor-pointer">Divisions</span>
          <span className="hover:text-white transition-colors cursor-pointer">Hackathons</span>
          <span className="hover:text-white transition-colors cursor-pointer">Projects</span>
          <span className="hover:text-white transition-colors cursor-pointer">Team</span>
        </div>
        <a 
          href="#contact" 
          className="px-5 py-2.5 rounded-full text-xs font-bold uppercase tracking-widest bg-white text-black hover:bg-[#FF9900] transition-all duration-300 shadow-[0_0_20px_rgba(255,255,255,0.1)]"
        >
          Join Portal
        </a>
      </header>

      {/* HERO SECTION */}
      <section className="relative min-h-screen flex flex-col justify-center items-center px-6 pt-32 pb-20 text-center">
        {/* Ambient background glow grids */}
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_80%_80%_at_50%_-20%,rgba(255,153,0,0.12),rgba(255,255,255,0))] pointer-events-none" />
        
        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white/[0.04] border border-white/10 mb-8 backdrop-blur-md">
          <span className="w-2 h-2 rounded-full bg-emerald-400 animate-ping" />
          <span className="text-xs font-medium tracking-wide text-white/80">Bahria University • Karachi (+5:00 GMT)</span>
        </div>

        <h1 className="font-['Syne'] font-extrabold text-5xl md:text-7xl lg:text-9xl tracking-tight max-w-6xl uppercase leading-[0.95] mb-8">
          From Students <br />
          <span className="text-transparent bg-clip-text bg-gradient-to-r from-[#FF9900] via-[#ffb84d] to-white">
            To Builders.
          </span>
        </h1>

        <p className="max-w-2xl text-base md:text-lg text-white/60 font-light leading-relaxed mb-12">
          AWS Student Builder Group @ Bahria University is a community of student developers learning cloud, AI, and modern software through hands-on building — not just theory.
        </p>

        <div className="flex flex-col sm:flex-row items-center gap-4">
          <a 
            href="#divisions" 
            className="w-full sm:w-auto px-8 py-4 rounded-full bg-[#FF9900] text-black font-bold text-sm uppercase tracking-wider hover:bg-white transition-all duration-300 shadow-[0_0_30px_rgba(255,153,0,0.3)]"
          >
            Explore Divisions
          </a>
          <a 
            href="#events" 
            className="w-full sm:w-auto px-8 py-4 rounded-full bg-white/[0.05] border border-white/10 text-white font-bold text-sm uppercase tracking-wider hover:bg-white/10 transition-all duration-300 backdrop-blur-md"
          >
            Upcoming Events
          </a>
        </div>
      </section>

      {/* INFINITE GREETING MARQUEE STRIP */}
      <div className="py-8 border-y border-white/10 bg-[#050505] overflow-hidden whitespace-nowrap">
        <div className="inline-flex gap-12 animate-[marquee_25s_linear_infinite] text-white/30 font-['Syne'] font-bold text-xl uppercase tracking-widest">
          <span>Hello</span> • <span>Namaste</span> • <span>Hola</span> • <span>Bonjour</span> • <span>Nǐn hǎo</span> • <span>Olá</span> • <span>Shalom</span> • <span>Ciao</span> • <span>Aloha</span> • <span>Xin Chào</span> • <span>Salaam</span> • <span>Zdraveĭte</span>
        </div>
      </div>

      {/* BENTO GRID DIVISIONS */}
      <section id="divisions" className="py-32 px-6 lg:px-16 max-w-7xl mx-auto">
        <div className="mb-20">
          <span className="text-[#FF9900] font-mono text-xs uppercase tracking-widest block mb-3">// Core Architecture</span>
          <h2 className="font-['Syne'] font-extrabold text-4xl md:text-6xl uppercase">From Code To Cloud</h2>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {/* Bento Card 1 - Main Large */}
          <div className="md:col-span-2 p-8 md:p-12 rounded-3xl bg-gradient-to-br from-white/[0.06] to-white/[0.02] border border-white/10 relative overflow-hidden group hover:border-[#FF9900]/50 transition-all duration-500">
            <div className="absolute top-0 right-0 p-8 font-['Syne'] font-extrabold text-7xl text-white/5 group-hover:text-[#FF9900]/10 transition-colors">01</div>
            <span className="text-xs font-mono text-[#FF9900] uppercase tracking-wider block mb-4">Division Alpha</span>
            <h3 className="font-['Syne'] font-bold text-2xl md:text-3xl mb-4 text-white">Cloud & AI Division</h3>
            <p className="text-white/60 leading-relaxed font-light mb-8 max-w-xl">
              Dive deep into cloud computing, artificial intelligence, and modern infrastructure. We conduct hands-on labs on AWS services, guiding you from cloud fundamentals to deploying generative AI applications. Through structured study groups and live architecture sessions, members gain hands-on expertise in EC2, Serverless (Lambda), SageMaker, and Cloud Security.
            </p>
            <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-[#FF9900]">
              <span>Explore Labs</span> →
            </div>
          </div>

          {/* Bento Card 2 */}
          <div className="p-8 md:p-12 rounded-3xl bg-gradient-to-br from-white/[0.06] to-white/[0.02] border border-white/10 relative overflow-hidden group hover:border-[#FF9900]/50 transition-all duration-500 flex flex-col justify-between">
            <div className="absolute top-0 right-0 p-8 font-['Syne'] font-extrabold text-7xl text-white/5 group-hover:text-[#FF9900]/10 transition-colors">02</div>
            <div>
              <span className="text-xs font-mono text-[#FF9900] uppercase tracking-wider block mb-4">Division Beta</span>
              <h3 className="font-['Syne'] font-bold text-2xl mb-4 text-white">Hackathons & Bootcamps</h3>
              <p className="text-white/60 leading-relaxed font-light text-sm">
                Intensive build sprints designed to push your limits, solve real-world problems, and ship production code under strict timelines.
              </p>
            </div>
            <div className="mt-8 text-xs font-bold uppercase tracking-widest text-white/40 group-hover:text-white transition-colors">View Sprints →</div>
          </div>

          {/* Bento Card 3 */}
          <div className="p-8 md:p-12 rounded-3xl bg-gradient-to-br from-white/[0.06] to-white/[0.02] border border-white/10 relative overflow-hidden group hover:border-[#FF9900]/50 transition-all duration-500 flex flex-col justify-between">
            <div className="absolute top-0 right-0 p-8 font-['Syne'] font-extrabold text-7xl text-white/5 group-hover:text-[#FF9900]/10 transition-colors">03</div>
            <div>
              <span className="text-xs font-mono text-[#FF9900] uppercase tracking-wider block mb-4">Division Gamma</span>
              <h3 className="font-['Syne'] font-bold text-2xl mb-4 text-white">Projects & Innovation Labs</h3>
              <p className="text-white/60 leading-relaxed font-light text-sm">
                Real AWS-powered products created by community builders, going from raw repository lines to deployed global cloud systems.
              </p>
            </div>
            <div className="mt-8 text-xs font-bold uppercase tracking-widest text-white/40 group-hover:text-white transition-colors">See Repos →</div>
          </div>

          {/* Bento Card 4 - Main Large */}
          <div className="md:col-span-2 p-8 md:p-12 rounded-3xl bg-gradient-to-br from-white/[0.06] to-white/[0.02] border border-white/10 relative overflow-hidden group hover:border-[#FF9900]/50 transition-all duration-500">
            <div className="absolute top-0 right-0 p-8 font-['Syne'] font-extrabold text-7xl text-white/5 group-hover:text-[#FF9900]/10 transition-colors">04</div>
            <span className="text-xs font-mono text-[#FF9900] uppercase tracking-wider block mb-4">Division Delta</span>
            <h3 className="font-['Syne'] font-bold text-2xl md:text-3xl mb-4 text-white">Community & Mentorship</h3>
            <p className="text-white/60 leading-relaxed font-light mb-8 max-w-xl">
              Connect with high-caliber student peers and industry leaders. We foster an environment where experience is shared openly, transforming raw talent into production-ready software engineers.
            </p>
            <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-[#FF9900]">
              <span>Join Network</span> →
            </div>
          </div>
        </div>
      </section>

      {/* EVENTS SECTION */}
      <section id="events" className="py-32 px-6 lg:px-16 max-w-7xl mx-auto border-t border-white/10">
        <div className="flex flex-col md:flex-row md:items-end justify-between mb-16">
          <div>
            <span className="text-[#FF9900] font-mono text-xs uppercase tracking-widest block mb-3">// Live Timeline</span>
            <h2 className="font-['Syne'] font-extrabold text-4xl md:text-6xl uppercase">Upcoming Events</h2>
          </div>
          <span className="text-white/40 text-sm mt-4 md:mt-0">Join workshops, hackathons & community meetups.</span>
        </div>

        <div className="space-y-4">
          {/* Event Item 1 */}
          <div className="p-8 rounded-2xl bg-white/[0.02] border border-white/10 flex flex-col md:flex-row md:items-center justify-between gap-6 hover:bg-white/[0.05] transition-all group">
            <div>
              <span className="inline-block px-3 py-1 rounded-full bg-[#FF9900]/10 text-[#FF9900] font-mono text-xs mb-3">Upcoming Event</span>
              <h3 className="font-['Syne'] font-bold text-2xl text-white group-hover:text-[#FF9900] transition-colors">Builders Connect</h3>
              <p className="text-white/60 text-sm mt-1">Talks about AWS & Cloud Careers with Hands-on Workshop.</p>
            </div>
            <button className="px-6 py-3 rounded-full bg-white text-black font-bold text-xs uppercase tracking-wider hover:bg-[#FF9900] transition-all">
              Reserve Seat
            </button>
          </div>

          {/* Event Item 2 */}
          <div className="p-8 rounded-2xl bg-white/[0.02] border border-white/10 flex flex-col md:flex-row md:items-center justify-between gap-6 hover:bg-white/[0.05] transition-all group">
            <div>
              <span className="inline-block px-3 py-1 rounded-full bg-white/10 text-white/70 font-mono text-xs mb-3">Upcoming Hackathon</span>
              <h3 className="font-['Syne'] font-bold text-2xl text-white group-hover:text-[#FF9900] transition-colors">Kirothon</h3>
              <p className="text-white/60 text-sm mt-1">Upcoming Hackathon — Themes & Dates To Be Decided.</p>
            </div>
            <button className="px-6 py-3 rounded-full bg-white/10 text-white font-bold text-xs uppercase tracking-wider hover:bg-white hover:text-black transition-all">
              Get Notified
            </button>
          </div>
        </div>
      </section>

      {/* CORE LEADERSHIP TEAM */}
      <section className="py-32 px-6 lg:px-16 max-w-7xl mx-auto border-t border-white/10">
        <div className="text-center max-w-2xl mx-auto mb-20">
          <span className="text-[#FF9900] font-mono text-xs uppercase tracking-widest block mb-3">// Leadership</span>
          <h2 className="font-['Syne'] font-extrabold text-4xl md:text-5xl uppercase mb-4">Our Creative Team</h2>
          <p className="text-white/60 text-sm">The minds powering AWS Student Builder Group at Bahria University.</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <div className="p-8 rounded-3xl bg-white/[0.02] border border-white/10 text-center group hover:border-[#FF9900]/40 transition-all">
            <div className="w-24 h-24 rounded-full bg-gradient-to-tr from-[#FF9900] to-purple-600 mx-auto mb-6 flex items-center justify-center font-['Syne'] font-bold text-2xl text-black shadow-lg">
              AA
            </div>
            <h3 className="font-['Syne'] font-bold text-xl text-white mb-1">Affan Bin Amir</h3>
            <p className="text-xs font-mono text-[#FF9900] uppercase tracking-wider">Captain AWSSBG</p>
          </div>

          <div className="p-8 rounded-3xl bg-white/[0.02] border border-white/10 text-center group hover:border-[#FF9900]/40 transition-all">
            <div className="w-24 h-24 rounded-full bg-gradient-to-tr from-blue-500 to-[#FF9900] mx-auto mb-6 flex items-center justify-center font-['Syne'] font-bold text-2xl text-black shadow-lg">
              WI
            </div>
            <h3 className="font-['Syne'] font-bold text-xl text-white mb-1">Waqas Ishaque</h3>
            <p className="text-xs font-mono text-[#FF9900] uppercase tracking-wider">Development Head</p>
          </div>

          <div className="p-8 rounded-3xl bg-white/[0.02] border border-white/10 text-center group hover:border-[#FF9900]/40 transition-all">
            <div className="w-24 h-24 rounded-full bg-gradient-to-tr from-purple-500 to-pink-500 mx-auto mb-6 flex items-center justify-center font-['Syne'] font-bold text-2xl text-black shadow-lg">
              HR
            </div>
            <h3 className="font-['Syne'] font-bold text-xl text-white mb-1">Huzaifa Rehman</h3>
            <p className="text-xs font-mono text-[#FF9900] uppercase tracking-wider">Management Head</p>
          </div>
        </div>
      </section>

      {/* CINEMATIC FOOTER */}
      <footer id="contact" className="bg-[#050505] border-t border-white/10 pt-24 pb-12 px-6 lg:px-16">
        <div className="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-16 pb-20 border-b border-white/10">
          <div>
            <span className="text-[#FF9900] font-mono text-xs uppercase tracking-widest block mb-3">// Let's Connect</span>
            <h2 className="font-['Syne'] font-extrabold text-4xl md:text-6xl uppercase mb-6">
              Let's bring your <br /> ideas to life!
            </h2>
            <p className="text-white/60 font-light">Ready to ship secure cloud systems and build world-class tech? Reach out to our core team directly.</p>
          </div>

          <div className="flex flex-col justify-start space-y-6">
            <div>
              <span className="text-xs font-mono text-white/40 uppercase block mb-1">Mail Us</span>
              <a href="mailto:hi@aws-sbgbu.com" className="font-['Syne'] font-bold text-xl md:text-2xl text-white hover:text-[#FF9900] transition-colors">
                hi@aws-sbgbu.com
              </a>
            </div>
            <div>
              <span className="text-xs font-mono text-white/40 uppercase block mb-1">Call Us At</span>
              <a href="tel:+923132458545" className="font-['Syne'] font-bold text-xl md:text-2xl text-white hover:text-[#FF9900] transition-colors">
                +92 313 2458545
              </a>
            </div>
          </div>
        </div>

        {/* Footer Bottom Bar */}
        <div className="max-w-7xl mx-auto pt-12 flex flex-col md:flex-row items-center justify-between gap-6 text-xs text-white/40">
          <div className="flex flex-wrap gap-6 uppercase tracking-widest font-semibold">
            <a href="#" className="hover:text-white transition-colors">LinkTree</a>
            <a href="#" className="hover:text-white transition-colors">Instagram</a>
            <a href="#" className="hover:text-white transition-colors">LinkedIn</a>
            <a href="#" className="hover:text-white transition-colors">Meetup</a>
            <a href="#" className="hover:text-white transition-colors">WhatsApp</a>
          </div>
          <div>
            Built with ♥︎ by Waqas Ishaque
          </div>
        </div>
      </footer>

      {/* Marquee Keyframes injection */}
      <style>{`
        @keyframes marquee {
          0% { transform: translateX(0%); }
          100% { transform: translateX(-50%); }
        }
      `}</style>
    </div>
  );
}